#ifndef GAMEPROTOCOL_PROTOCOL_DEFINITION_ID_H
#define GAMEPROTOCOL_PROTOCOL_DEFINITION_ID_H

/* THERE CAN ABSOLUTLEY NOT BE TWO DEFINITIONS WITH THE SAME ID!! */

#define protocol_PlayerNavigation	0;

#endif // !GAMEPROTOCOL_PROTOCOL_DEFINITION_ID_H
